/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestauracaoRouteImport } from './routes/restauracao'
import { Route as MuseuRouteImport } from './routes/museu'
import { Route as InstitutoRouteImport } from './routes/instituto'
import { Route as HerculesGalloRouteImport } from './routes/hercules-gallo'
import { Route as GalopolisRouteImport } from './routes/galopolis'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovidadesIndexRouteImport } from './routes/novidades.index'
import { Route as GaleriaIndexRouteImport } from './routes/galeria.index'
import { Route as NovidadesIdRouteImport } from './routes/novidades.$id'
import { Route as GaleriaIdRouteImport } from './routes/galeria.$id'

const RestauracaoRoute = RestauracaoRouteImport.update({
  id: '/restauracao',
  path: '/restauracao',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseuRoute = MuseuRouteImport.update({
  id: '/museu',
  path: '/museu',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutoRoute = InstitutoRouteImport.update({
  id: '/instituto',
  path: '/instituto',
  getParentRoute: () => rootRouteImport,
} as any)
const HerculesGalloRoute = HerculesGalloRouteImport.update({
  id: '/hercules-gallo',
  path: '/hercules-gallo',
  getParentRoute: () => rootRouteImport,
} as any)
const GalopolisRoute = GalopolisRouteImport.update({
  id: '/galopolis',
  path: '/galopolis',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesIndexRoute = NovidadesIndexRouteImport.update({
  id: '/novidades/',
  path: '/novidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaIndexRoute = GaleriaIndexRouteImport.update({
  id: '/galeria/',
  path: '/galeria/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesIdRoute = NovidadesIdRouteImport.update({
  id: '/novidades/$id',
  path: '/novidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaIdRoute = GaleriaIdRouteImport.update({
  id: '/galeria/$id',
  path: '/galeria/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/atividades': typeof AtividadesRoute
  '/contato': typeof ContatoRoute
  '/editor': typeof EditorRoute
  '/galopolis': typeof GalopolisRoute
  '/hercules-gallo': typeof HerculesGalloRoute
  '/instituto': typeof InstitutoRoute
  '/museu': typeof MuseuRoute
  '/restauracao': typeof RestauracaoRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/novidades/$id': typeof NovidadesIdRoute
  '/galeria/': typeof GaleriaIndexRoute
  '/novidades/': typeof NovidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/atividades': typeof AtividadesRoute
  '/contato': typeof ContatoRoute
  '/editor': typeof EditorRoute
  '/galopolis': typeof GalopolisRoute
  '/hercules-gallo': typeof HerculesGalloRoute
  '/instituto': typeof InstitutoRoute
  '/museu': typeof MuseuRoute
  '/restauracao': typeof RestauracaoRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/novidades/$id': typeof NovidadesIdRoute
  '/galeria': typeof GaleriaIndexRoute
  '/novidades': typeof NovidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/atividades': typeof AtividadesRoute
  '/contato': typeof ContatoRoute
  '/editor': typeof EditorRoute
  '/galopolis': typeof GalopolisRoute
  '/hercules-gallo': typeof HerculesGalloRoute
  '/instituto': typeof InstitutoRoute
  '/museu': typeof MuseuRoute
  '/restauracao': typeof RestauracaoRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/novidades/$id': typeof NovidadesIdRoute
  '/galeria/': typeof GaleriaIndexRoute
  '/novidades/': typeof NovidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/atividades'
    | '/contato'
    | '/editor'
    | '/galopolis'
    | '/hercules-gallo'
    | '/instituto'
    | '/museu'
    | '/restauracao'
    | '/galeria/$id'
    | '/novidades/$id'
    | '/galeria/'
    | '/novidades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/atividades'
    | '/contato'
    | '/editor'
    | '/galopolis'
    | '/hercules-gallo'
    | '/instituto'
    | '/museu'
    | '/restauracao'
    | '/galeria/$id'
    | '/novidades/$id'
    | '/galeria'
    | '/novidades'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/atividades'
    | '/contato'
    | '/editor'
    | '/galopolis'
    | '/hercules-gallo'
    | '/instituto'
    | '/museu'
    | '/restauracao'
    | '/galeria/$id'
    | '/novidades/$id'
    | '/galeria/'
    | '/novidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AtividadesRoute: typeof AtividadesRoute
  ContatoRoute: typeof ContatoRoute
  EditorRoute: typeof EditorRoute
  GalopolisRoute: typeof GalopolisRoute
  HerculesGalloRoute: typeof HerculesGalloRoute
  InstitutoRoute: typeof InstitutoRoute
  MuseuRoute: typeof MuseuRoute
  RestauracaoRoute: typeof RestauracaoRoute
  GaleriaIdRoute: typeof GaleriaIdRoute
  NovidadesIdRoute: typeof NovidadesIdRoute
  GaleriaIndexRoute: typeof GaleriaIndexRoute
  NovidadesIndexRoute: typeof NovidadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restauracao': {
      id: '/restauracao'
      path: '/restauracao'
      fullPath: '/restauracao'
      preLoaderRoute: typeof RestauracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museu': {
      id: '/museu'
      path: '/museu'
      fullPath: '/museu'
      preLoaderRoute: typeof MuseuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituto': {
      id: '/instituto'
      path: '/instituto'
      fullPath: '/instituto'
      preLoaderRoute: typeof InstitutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hercules-gallo': {
      id: '/hercules-gallo'
      path: '/hercules-gallo'
      fullPath: '/hercules-gallo'
      preLoaderRoute: typeof HerculesGalloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galopolis': {
      id: '/galopolis'
      path: '/galopolis'
      fullPath: '/galopolis'
      preLoaderRoute: typeof GalopolisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades/': {
      id: '/novidades/'
      path: '/novidades'
      fullPath: '/novidades/'
      preLoaderRoute: typeof NovidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/': {
      id: '/galeria/'
      path: '/galeria'
      fullPath: '/galeria/'
      preLoaderRoute: typeof GaleriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades/$id': {
      id: '/novidades/$id'
      path: '/novidades/$id'
      fullPath: '/novidades/$id'
      preLoaderRoute: typeof NovidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/$id': {
      id: '/galeria/$id'
      path: '/galeria/$id'
      fullPath: '/galeria/$id'
      preLoaderRoute: typeof GaleriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AtividadesRoute: AtividadesRoute,
  ContatoRoute: ContatoRoute,
  EditorRoute: EditorRoute,
  GalopolisRoute: GalopolisRoute,
  HerculesGalloRoute: HerculesGalloRoute,
  InstitutoRoute: InstitutoRoute,
  MuseuRoute: MuseuRoute,
  RestauracaoRoute: RestauracaoRoute,
  GaleriaIdRoute: GaleriaIdRoute,
  NovidadesIdRoute: NovidadesIdRoute,
  GaleriaIndexRoute: GaleriaIndexRoute,
  NovidadesIndexRoute: NovidadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
